catpage/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('kociapani/', admin.site.urls),
    path('', include('sheerjoy.urls')),
]

sheerjoy/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'sheerjoy'

urlpatterns = [
    path('', views.index, name="index"),
    path('koty/', views.koty, name="koty"),
    path('gallery/', views.gallery, name="gallery"),
    path('felinoterapia/', views.felinoterapia, name="felinoterapia"),
    path('dyplomy/', views.dyplomy, name="dyplomy"),
    path('pawpeds/', views.pawpeds, name="pawpeds"),
    path('seminaria/', views.seminaria, name="seminaria"),
    path('mioty/',  views.mioty, name="mioty"),
    path('miot/<int:id>', views.miot, name="miot")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sheerjoy/models.py
from django.db import models
from django.core.files.uploadedfile import InMemoryUploadedFile

from PIL import Image
from io import StringIO, BytesIO
from datetime import datetime
from sys import getsizeof


class AnimalColoration(models.Model):
    name = models.CharField(max_length=50, null=False)
    short = models.CharField(max_length=3, null=True)
    number = models.SmallIntegerField(default=0)

    def __str__(self):
        return f'{self.short}{self.number} - {self.name}'


class Culture(models.Model):
    name = models.CharField(max_length=50, null=False)

    def __str__(self):
        return f'{self.name}'


class Title(models.Model):
    short = models.CharField(max_length=10, null=False)
    name = models.CharField(max_length=40, null=False)

    def __str__(self):
        return f'{self.short} - {self.name}'

    def to_description(self):
        return f'{self.short}'


class Citation(models.Model):
    name = models.CharField(max_length=500)
    author = models.CharField(max_length=50, null=True, blank=True)


def fit_image_profile(picture):
    img = Image.open(picture)
    if img.mode != 'RGB':
        img = img.convert('RGB')
    area = tuple()
    if picture.width >= 5 * picture.height / 3:
        x = picture.width - 5 * picture.height / 3
        area = (x/2, 0, x/2 + 5 * picture.height / 3, picture.height)
    else:
        y = picture.height - 3 * picture.width / 5
        area = (0, y/2, picture.width, y/2 + 3*picture.width/5)
    print(area)
    img = img.crop(area)
    img.thumbnail((img.width, img.height), Image.ANTIALIAS)
    output = BytesIO()
    img.save(output, format='JPEG', quality=80)
    output.seek(0)
    return InMemoryUploadedFile(output, 'ImageField',
                                f"{picture.name.split('.')[0]}_min.jpeg",
                                'image/jpeg', getsizeof(output), None)


class CatProfile(models.Model):
    name = models.CharField(max_length=30, null=True)
    image = models.ImageField(upload_to='profile/', null=True, blank=True, default=None)
    culture = models.ForeignKey(Culture, related_name='cats', null=True, default=None, blank=True, on_delete=models.SET_NULL)
    color = models.ForeignKey(AnimalColoration, on_delete=models.SET_NULL, null=True)
    description = models.CharField(max_length=500, null=True, blank=True)
    mother = models.ForeignKey('self', related_name='born', null=True, default=None, blank=True, on_delete=models.SET_NULL)
    father = models.ForeignKey('self', related_name='impregnated', null=True, default=None, blank=True, on_delete=models.SET_NULL)
    sexes = [('1,0', 'Male'), ('0,1', 'Female')]
    sex = models.CharField(max_length=5, choices=sexes, null=True, default=None)
    title = models.ForeignKey(Title, related_name='laureate', null=True, default=None, blank=True, on_delete=models.SET_NULL)
    birth = models.DateField(blank=True, null=True, default=None)
    weight = models.SmallIntegerField(default=0, null=True, blank=True)
    litter = models.ForeignKey('Litter',  related_name='family', null=True, blank=True, on_delete=models.SET_NULL)
    is_with_us = models.BooleanField(default=True)
    display = models.BooleanField(default=True)

    def check_title(self):
        return f'{self.title.short} ' if self.title else ''

    def check_culture(self):
        return f'{self.culture} ' if self.color else ' '

    def sex_explanation(self):
        return 'kocur' if self.sex == '1,0' else 'kotka'

    def life_time(self):
        if self.birth:
            delta = (datetime.date(datetime.now()) - self.birth).days
            if delta == 1:
                return f'{delta} dzień'
            if delta < 22:
                return f'{delta} dni'
            if delta < 35:
                return f'{int(delta/7)} tygodnie'
            if delta < 106:
                return f'{int(delta / 7)} tygodni'
            if delta < 800:
                return f'{(datetime.now().year - self.birth.year) * 12 + (datetime.now().month - self.birth.month)} miesięcy'
            return f'{(datetime.now().year - self.birth.year)} lata'
        return ''

    def __str__(self):
        return f'{self.check_title()}{self.name} {self.check_culture()}{self.color}'

    def save(self, *args, **kwargs):
        self.image = fit_image_profile(self.image) if self.image else None
        super(CatProfile, self).save(*args, **kwargs)


class Litter(models.Model):
    name = models.CharField(max_length=30, null=True)
    mother = models.ForeignKey(CatProfile, related_name='+', null=True, on_delete=models.SET_NULL,
                               limit_choices_to={'sex': '0,1'})
    father = models.ForeignKey(CatProfile, related_name='+', null=True, on_delete=models.SET_NULL,
                               limit_choices_to={'sex': '1,0'})
    birth = models.DateField(blank=True, null=True, default=None)

    def __str__(self):
        return f'{self.name} {self.birth}'


class LitterPhoto(models.Model):
    name = models.CharField(max_length=30, null=True, blank=True)
    image = models.ImageField(upload_to='litter/')


class Kitten(models.Model):
    name = models.CharField(max_length=30, null=True, blank=True)
    image = models.ImageField(upload_to='kitten/', blank=True)
    litter = models.ForeignKey(Litter, related_name='children', null=True, blank=True, on_delete=models.SET_NULL)

    def save(self, *args, **kwargs):
        self.image = fit_image(self.image) if self.image else None
        super(Kitten, self).save(*args, **kwargs)


class HashTag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return f'{self.name}'


def fit_image(picture):
    img = Image.open(picture)
    if img.mode != 'RGB':
        img = img.convert('RGB')
    img.thumbnail((picture.width / 1.5, picture.height / 1.5), Image.ANTIALIAS)
    output = BytesIO()
    img.save(output, format='JPEG', quality=80)
    output.seek(0)
    return InMemoryUploadedFile(output, 'ImageField',
                                f"{picture.name.split('.')[0]}.jpeg",
                                'image/jpeg', getsizeof(output), None)


def fit_image_miniature(picture):
    img = Image.open(picture)
    if img.mode != 'RGB':
        img = img.convert('RGB')
    img.thumbnail((350, int((350/picture.width) * picture.height)), Image.ANTIALIAS)
    output = BytesIO()
    img.save(output, format='JPEG', quality=80)
    output.seek(0)
    return InMemoryUploadedFile(output, 'ImageField',
                                f"{picture.name.split('.')[0]}_min.jpeg",
                                'image/jpeg', getsizeof(output), None)


class Gallery(models.Model):
    name = models.CharField(max_length=50, null=True, blank=True)
    image = models.ImageField(upload_to='gallery/')
    image_min = models.ImageField(upload_to='gallery/min/', default=None, blank=True)
    who_is_in = models.ManyToManyField(CatProfile, related_name='on_picture', blank=True)
    tag = models.ManyToManyField(HashTag, related_name='photos', blank=True)

    def __str__(self):
        return f'{self.image} {self.name}'

    def save(self, *args, **kwargs):
        self.image_min = fit_image_miniature(self.image)
        self.image = fit_image(self.image) if self.image else None
        super(Gallery, self).save(*args, **kwargs)

    def get_filters(self):
        result = ''
        if self.tag:
            filters = ['filter-'+tag.name for tag in self.tag.all()]
            for filter in filters:
                result = result + f' {filter}'
        return f'{result}'

    def get_hashtags(self):
        result = ''
        if self.tag:
            filters = ['#'+tag.name for tag in self.tag.all()]
            for filter in filters:
                result = result + f' {filter}'
        return f'{result}'


class HomeGallery(models.Model):
    name = models.CharField(max_length=50, null=True, blank=True)
    image = models.ImageField(upload_to='home/')




sheerjoy/views.py
from django.http import HttpResponse
from django.template import loader
from django.shortcuts import render
from . import models
from datetime import datetime
from random import sample, choice


def index(request):
    template = loader.get_template("home.html")
    about_pictures = models.Gallery.objects.order_by('?')[:4]
    citation = models.Citation.objects.order_by('?').first()
    print(citation.name)
    context = {
        'about_pictures': about_pictures,
        'citation': citation
    }
    return render(request, 'home.html', context)


def koty(request):
    template = loader.get_template("koty.html")
    all = models.CatProfile.objects.filter(display=True)
    cats = all.filter(sex='1,0')
    kitten = all.filter(sex='0,1')
    context = {
        'cats': cats,
        'kitten': kitten,
    }
    return HttpResponse(template.render(context, request))


def mioty(request):
    template = loader.get_template("mioty.html")
    # excepted_litters = models.Litter.objects.filter(birth__gte=datetime.today())
    # litters = models.Litter.objects.exclude(birth__gte=datetime.today()).order_by('-birth')
    # context = {
    #     'excepted_litters': excepted_litters,
    #     'litters': litters
    # }
    return HttpResponse(template.render({}, request))


def miot(request, id):
    template = loader.get_template("miot.html")
    litter = models.Litter.objects.get(pk=id)
    context = {
        'litter': litter
    }
    return HttpResponse(template.render(context, request))


def gallery(request):
    template = loader.get_template("gallery.html")
    photos = models.Gallery.objects.all()
    hashtags = models.HashTag.objects.all()

    context = {
        'photos': photos,
        'hashtags': hashtags,
    }
    return HttpResponse(template.render(context, request))


def felinoterapia(request):
    template = loader.get_template("felinoterapia.html")
    return HttpResponse(template.render(dict(), request))


def dyplomy(request):
    template = loader.get_template("dyplomy.html")
    return HttpResponse(template.render(dict(), request))


def pawpeds(request):
    template = loader.get_template("pawpeds.html")
    return HttpResponse(template.render(dict(), request))


def seminaria(request):
    template = loader.get_template("seminaria.html")
    return HttpResponse(template.render(dict(), request))



sheerjoy/templates/base.html
<!DOCTYPE html>
<html lang="pl">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-164034591-1"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'UA-164034591-1');
    </script>

    <title>Hodowla Kotów Syberyjskich SheerJoy*PL</title>
    <meta name="description"
          content="domowa Hodowla Kotów Syberyjskich SheerJoy SheerJoy*PL koty rasowe Łabiszyn  ">
    <meta name="keywords" content="domowa Hodowla Kotów Syberyjskich SheerJoy kot koty kotki syberyjskie cats ">
    {% load  %}

    <!-- Favicons -->
    <link href="{% static 'assets/img/ikonka.png' %}" rel="icon">
    <link href="{% static 'assets/img/ikonka.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Montserrat:300,400,500,600,700"
          rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/ionicons/css/ionicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/venobox/venobox.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/owl.carousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/media.css' %}" rel="stylesheet">

    <script src="{% static 'assets/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/jquery.easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/vendor/counterup/counterup.min.js' %}"></script>
    <script src="{% static 'assets/vendor/venobox/venobox.min.js' %}"></script>
    <script src="{% static 'assets/vendor/wow/wow.min.js' %}"></script>
    <script src="{% static 'assets/vendor/owl.carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/vendor/waypoints/jquery.waypoints.min.js' %}"></script>

    {% block head %}

    {% endblock %}
</head>

<body>


<header id="header">
    <div class="container">
        <div class="float-left">
            <a href="{% url 'sheerjoy:index' %}">
                <img src="{% static 'assets/img/baner2_100.png' %}" class="img-fluid" style="max-width: 200px; height: auto;" alt="ikonka">
            </a>
        </div>

        <nav class="main-nav float-right d-none d-lg-block">
            <ul>
                <li class="active"><a href="{% url 'sheerjoy:index' %}">hodowla</a></li>
                <li class="drop-down"><a href="{% url 'sheerjoy:koty' %}">nasze koty</a>
                    <ul>
                        <li><a href="{% url 'sheerjoy:koty' %}#kotki">kotki</a></li>
                        <li><a href="{% url 'sheerjoy:koty' %}#kocury">kocury</a>
                        <li class="inactive"><a href="#">kocięta</a>
                    </ul>
                </li>
                <li><a href="{% url 'sheerjoy:gallery' %}">galeria</a></li>
                <li class="drop-down"><a href="{% url 'sheerjoy:mioty' %}">mioty</a>
                    <ul>
                        <li><a href="{% url 'sheerjoy:mioty' %}#spodziewane">spodziewane</a></li>
                        <li><a href="{% url 'sheerjoy:mioty' %}#mioty">poprzednie</a>
                    </ul>
                </li>
                <li><a href="#kontakt">kontakt</a></li>
            </ul>
        </nav>
    </div>

    <script src="{% static 'assets/vendor/mobile-nav/mobile-nav.js' %}"></script>
</header>

{% block hero %}

{% endblock %}

<!-- End Hero -->

<main id="main">
    {% block content %}

    {% endblock %}
</main>
<!-- End #main -->

<!-- ======= Footer ======= -->
<footer id="footer" class="section-bg">
    <div id="kontakt" class="footer-top">
    <header class="section-header">
            <h3 class="section-title">Kontakt</h3>
    </header>
        <div class="container">
            <div class="row">

                <div class="col-md-8">
                    <iframe id="map" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2404.109601995371!2d17.920392215823384!3d52.946450879897064!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xb20f6b147e7a87b5!2sHodowla%20Kot%C3%B3w%20Syberyjskich%20SheerJoy*2APL!5e0!3m2!1spl!2spl!4v1588615082808!5m2!1spl!2spl"
                            frameborder="0" height="400" style="border:0; width:inherit" allowfullscreen=""
                            aria-hidden="false" tabindex="0">
                    </iframe>
                </div>

                <div class="col-md-4 p-3">
                    <div class="info d-flex flex-column justify-content-center" data-aos="fade-right">
                        <div class="address">
                            <i class="icofont-google-map"></i>
                            <h4>Adres:</h4>
                            <p>Łabiszyn Wieś 20A</p>
                            <p>89-210 Łabiszyn</p>
                        </div>

                        <div class="email">
                            <i class="icofont-envelope"></i>
                            <h4>Email:</h4>
                            <p>sheerjoypl@gmail.com</p>
                        </div>

                        <div class="phone">
                            <i class="icofont-phone"></i>
                            <h4>Telefon:</h4>
                            <p>+48 600 302 663</p>
                        </div>

                    </div>
                </div>
            </div>

        </div>
    </div>
    <div class="container">

        <div class="copyright">
            &copy; Copyright <strong>Hodowla kotów syberyjskich SheerJoy*PL</strong>
        </div>
        <div class="credits">
            Designed by Rafał Kowalewski
        </div>
    </div>
</footer><!-- End  Footer -->

<a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
<script src="{% static 'assets/js/main.js' %}"></script>

</body>
</html>

sheerjoy/templates/blank_template.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block head %}

{% endblock %}

{% block hero %}

{% endblock %}

{% block content %}

{% endblock %}

sheerjoy/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
<link href="{% static 'assets/css/custom.css' %}" rel="stylesheet">
{% endblock %}

{% block hero %}
<section id="hero" class="clearfix">
    <div class="container d-flex h-100">
        <div class="row justify-content-center align-self-center">
            <div class="col-md-6 intro-info order-md-first order-last">
                <h2><span>{{ citation.name }}</span></h2>
                <div>
                    <a href="https://www.facebook.com/Hodowla-Kot%C3%B3w-Syberyjskich-Sheer-JoyPl-1937100613234165/"
                       class="facebook"><h3>Zobacz nasz profil na</h3><h4>Facebooku <i class="fa fa-facebook"></i></h4>
                    </a>
                </div>
            </div>
            <div class="col-md-6 intro-img order-md-last order-first">
                <img src="{% static 'assets/img/logo/logo_slonce_czarne_40.png' %}" alt="cat_with_computer" class="img-fluid">
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block content %}

<section id="about" class="about">
    <div class="container">
        <div class="row">
            {% if about_pictures %}
            <div class="col-lg-5 col-md-6">
                <div class="about-img">
                    <a href="{% url 'sheerjoy:gallery' %}">
                        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                {% for picture in about_pictures %}
                                <li data-target="#carouselExampleIndicators" data-slide-to="{{ forloop.counter }}"></li>
                                {% endfor %}
                            </ol>
                            <div class="carousel-inner">
                                {% for picture in about_pictures %}
                                <div class="carousel-item {% if forloop.counter == 1 %}active{% endif %} }}">
                                    <img src="{{ picture.image_min.url }}" alt="{{ picture.name }}" class="img-fluid">
                                </div>

                                {% endfor %}
                            </div>
                            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button"
                               data-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button"
                               data-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </a>
                </div>
                <a href="{% url 'sheerjoy:gallery' %}"><h3 class="text-center">zobacz całą galerię...</h3></a>
            </div>
            {% endif %}
            <div class="col-lg-7 col-md-6">
                <div class="about-content">
                    <h2>O hodowli</h2>
                    <h3> Z kotami do czynienia miałam już od wczesnego dzieciństwa, jako że wychowałam się na wsi. Były
                        to jednak koty na pół dzikie, takie, które podchodziły bliżej tylko, kiedy pachniało jedzenie.
                        Pierwszego kociego mieszkańca naszego domu powitaliśmy w dniu I Komunii Świętej mojej starszej
                        córki- była to ruda, piękna i złośliwa persiczka. </h3>
                    <p> To wtedy zakochałam się w kotach. Gdy po 8 latach jej zabrakło, kupiliśmy britkę,
                        którą, jak się po miesiącu okazało,dostaliśmy „w pakiecie” z FIP-em. Po kolejnym miesiącu
                        leczenia, wizyt u weterynarzy, ściągania płynu i innych traumatycznych przeżyć, musieliśmy ją
                        pożegnać. Wtedy też postanowiłam nie angażować się już w życie z kotami domowymi. Mieliśmy
                        zawsze w obejściu jednego lub kilka półdzikusków, o które dbaliśmy. To miało wystarczyć. </p>
                    <p> Wystarczyło. Na całe sześć tygodni. Kiedy pewnego dnia przeglądałam strony z kotami, zobaczyłam
                        JĄ- Gaję. I już wiedziałam, że to na nią czekałam. Od niej zaczęła się nie tylko moja miłość do
                        kotów syberyjskich- najwspanialszych przedstawicieli kotów, ale i zainteresowanie wystawami,
                        pokazami, a w końcu też hodowlą. Początkowo próbowałam sił jako współhodowca, jednak wkrótce
                        zapragnęłam mieć coś tylko swojego. I tak powstała domowa, pełna czystej miłości i radości
                        hodowla Sheer Joy*PL. </p>
                    <ul>
                        <li><i class="ion-android-checkmark-circle"></i>Nasze koty to pełnoprawni domownicy,
                            rozpieszczani, otaczani troską i miłością i wspaniale zsocjalizowani.
                        </li>
                        <li><i class="ion-android-checkmark-circle"></i>Koty w naszej hodowli są zdrowe, regularnie
                            badane, wolne od FeLV, FiV. Opiekę weterynaryjną nad nimi sprawuje gabinet weterynaryjny
                            ‘Brzoza’ w Brzozie Bydgoskiej oraz klinika weterynaryjna ‘Kora’ w Bydgoszczy.
                        </li>
                        <li><i class="ion-android-checkmark-circle"></i>Hodowla jest członkiem klubu IBSCC pod
                            auspicjami WCF (World Cat Federation), międzynarodowej organizacji felinologicznej.
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="call-to-action" class="call-to-action wow fadeInUp">
    <div class="container">
        <div class="row">
            <div class="col-lg-1 d-sm-none d-lg-block">
                <img class="img-fluid " alt="dyplom"
                     src="{% static 'assets/img/diplomas/32242885_1796106857108277_2913589574611501056_n.gif' %}"/>
            </div>
            <div class="col-lg-7 text-center text-lg-left">
                <h3 class="cta-title">Pawpeds</h3>
                <p class="cta-text pl-3"> Dzięki kursowi Pawpeds G1 znacznie pogłębiłam swoją wiedzę na temat posiadania
                    kota i prowadzenia hodowli.</p>
            </div>
            <div class="col-lg-4 cta-btn-container text-center">
                <a class="cta-btn align-middle" href="{% url 'sheerjoy:pawpeds' %}">czytaj więcej</a>
            </div>
        </div>
        <hr/>
        <div class="row">
            <div class="col-lg-1"></div>
            <div class="col-lg-8">
                <h3 class="cta-title text-center text-lg-right">Szkolenia i certyfikaty</h3>
                <p class="cta-text pl-3"> Cały czas poszerzam wiedzę o prowadzeniu hodowlii nie tylko z życia ale i
                    profesjonalnych szkoleń </p>
                <p class="cta-text pl-3"> Zobacz moje certyfikaty i odznaczenia... </p>
            </div>
            <div class="col-lg-3 cta-btn-container text-center text-lg-left order-lg-first float-lg-left">
                <a class="cta-btn align-middle " href="{% url 'sheerjoy:dyplomy' %}">czytaj więcej</a>
            </div>
        </div>
        <hr/>
        <div class="row">
            <div class="col-lg-8 text-center text-lg-left">
                <h3 class="cta-title">Felinoterapia</h3>
                <p class="cta-text pl-3"> Ukończyłam kurs felinoterapii, terapii kontaktowej z wykorzystaniem
                    kotów...</p>
            </div>
            <div class="col-lg-4 cta-btn-container text-center">
                <a class="cta-btn align-middle" href="{% url 'sheerjoy:felinoterapia' %}">czytaj więcej</a>
            </div>
        </div>
        <hr/>
        <div class="row">
            <div class="col-lg-1"></div>
            <div class="col-lg-8">
                <h3 class="cta-title text-center text-lg-right">Seminaria Felinologiczne</h3>
                <p class="cta-text pl-3"> Seminaria felinologiczne to istna kopalnia informacji zarówno teoretycznych,
                    jaki praktycznych. Wykłady i rozmowy ze znakomitymi profesorami i znawcami kotów pozwalają mi
                    spojrzeć na pewne aspekty prowadzenia hodowli i postępowania wobec moich kocich domowników z innej,
                    szerszej perspektywy </p>
            </div>
            <div class="col-lg-3 cta-btn-container text-center text-lg-left order-lg-first float-lg-left">
                <a class="cta-btn align-middle " href="{% url 'sheerjoy:seminaria' %}">czytaj więcej</a>
            </div>
        </div>
    </div>
</section>


<section id="services" class="services section-bg">
    <div class="container">

        <header class="section-header">
            <h3>Stowarzyszenia</h3>
            <p>Nasza hodowla jest członkiem organizacji </p>
        </header>

        <div class="row">

            <div class="col-md-6 col-lg-4 wow bounceInUp" data-wow-duration="1.4s">
                <div class="box">
                    <div class="icon" style="background: #fceef3;"><img src="{% static 'assets/img/ibscc.png' %}"
                                                                        class="img-fluid"></div>
                    <h4 class="title"><a href="http://ibscc.pl/">IBSCC</a></h4>
                    <p class="description">International British Shorthair Cat Club</p>
                </div>
            </div>
            <div class="col-md-6 col-lg-4 wow bounceInUp" data-wow-duration="1.4s">
                <div class="box">
                    <div class="icon" style="background: #fff0da;"><img src="{% static 'assets/img/wcf.png' %}"
                                                                        class="img-fluid"></div>
                    <h4 class="title"><a href="http://www.wcf-online.de/">WCF</a></h4>
                    <p class="description">World Cat Federation</p>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

sheerjoy/templates/mioty.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}

{% block head %}
<style>
    @media (min-width: 576px) {
        .table-kot {
            font-size: 24px;
        }
    }

    @media (min-width: 768px) {
        .table-kot {
            font-size: 20px;
        }
    }

    @media (min-width: 992px) {
        .table-kot {
            font-size: 18px;
        }
    }


</style>
{% endblock %}

{% block content %}



<section id="incoming" class="services section-bg" style="padding-top: 60px;">
    <div class="container">


    <p>hej</p>
    </div>
</section>
{% endblock %}